version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: wiki
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: wiki
    ports:
      - "5432:5432"
      
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/postgresql/data 

networks:
  my-network:
    driver: bridge

volumes:
  db_data: 
