services:
  
  db:
    image: postgres:16-alpine
    container_name: wiki_db
    
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=wiki
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  
  app:
    build: .
    container_name: wiki_apl
    environment:
      - DATABASE_URL=postgres://DB_USER:DB_PASS@db:5432/wiki?sslmode=disable
    depends_on:
      - db
    ports:
      - "9000:9000"
    command: ["./main"]

volumes:
  postgres_data: